package com.example.meetfake.model;

import java.util.Date;

public class Room {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_room.id
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_room.roomId
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	private String roomid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_room.title
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_room.status
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_room.host
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	private Long host;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_room.created_at
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_room.updated_at
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	private Date updatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_room.start
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	private String start;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_room.end
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	private String end;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_room.startTime
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	private String starttime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_room.endTime
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	private String endtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_room.daysOfWeek
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	private String daysofweek;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_room.id
	 * @return  the value of tbl_room.id
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_room.id
	 * @param id  the value for tbl_room.id
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_room.roomId
	 * @return  the value of tbl_room.roomId
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public String getRoomid() {
		return roomid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_room.roomId
	 * @param roomid  the value for tbl_room.roomId
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public void setRoomid(String roomid) {
		this.roomid = roomid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_room.title
	 * @return  the value of tbl_room.title
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_room.title
	 * @param title  the value for tbl_room.title
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_room.status
	 * @return  the value of tbl_room.status
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_room.status
	 * @param status  the value for tbl_room.status
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_room.host
	 * @return  the value of tbl_room.host
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public Long getHost() {
		return host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_room.host
	 * @param host  the value for tbl_room.host
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public void setHost(Long host) {
		this.host = host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_room.created_at
	 * @return  the value of tbl_room.created_at
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_room.created_at
	 * @param createdAt  the value for tbl_room.created_at
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_room.updated_at
	 * @return  the value of tbl_room.updated_at
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_room.updated_at
	 * @param updatedAt  the value for tbl_room.updated_at
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_room.start
	 * @return  the value of tbl_room.start
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public String getStart() {
		return start;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_room.start
	 * @param start  the value for tbl_room.start
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public void setStart(String start) {
		this.start = start;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_room.end
	 * @return  the value of tbl_room.end
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public String getEnd() {
		return end;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_room.end
	 * @param end  the value for tbl_room.end
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public void setEnd(String end) {
		this.end = end;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_room.startTime
	 * @return  the value of tbl_room.startTime
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public String getStarttime() {
		return starttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_room.startTime
	 * @param starttime  the value for tbl_room.startTime
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public void setStarttime(String starttime) {
		this.starttime = starttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_room.endTime
	 * @return  the value of tbl_room.endTime
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public String getEndtime() {
		return endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_room.endTime
	 * @param endtime  the value for tbl_room.endTime
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public void setEndtime(String endtime) {
		this.endtime = endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_room.daysOfWeek
	 * @return  the value of tbl_room.daysOfWeek
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public String getDaysofweek() {
		return daysofweek;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_room.daysOfWeek
	 * @param daysofweek  the value for tbl_room.daysOfWeek
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public void setDaysofweek(String daysofweek) {
		this.daysofweek = daysofweek;
	}
}