package com.example.meetfake.model;

import java.util.Date;

public class RoomDetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_room_detail.id
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_room_detail.room_id
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	private Long roomId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_room_detail.user_id
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_room_detail.auth
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	private String auth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_room_detail.created_at
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_room_detail.updated_at
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_room_detail.id
	 * @return  the value of tbl_room_detail.id
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_room_detail.id
	 * @param id  the value for tbl_room_detail.id
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_room_detail.room_id
	 * @return  the value of tbl_room_detail.room_id
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public Long getRoomId() {
		return roomId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_room_detail.room_id
	 * @param roomId  the value for tbl_room_detail.room_id
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public void setRoomId(Long roomId) {
		this.roomId = roomId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_room_detail.user_id
	 * @return  the value of tbl_room_detail.user_id
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_room_detail.user_id
	 * @param userId  the value for tbl_room_detail.user_id
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_room_detail.auth
	 * @return  the value of tbl_room_detail.auth
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public String getAuth() {
		return auth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_room_detail.auth
	 * @param auth  the value for tbl_room_detail.auth
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public void setAuth(String auth) {
		this.auth = auth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_room_detail.created_at
	 * @return  the value of tbl_room_detail.created_at
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_room_detail.created_at
	 * @param createdAt  the value for tbl_room_detail.created_at
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_room_detail.updated_at
	 * @return  the value of tbl_room_detail.updated_at
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_room_detail.updated_at
	 * @param updatedAt  the value for tbl_room_detail.updated_at
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}