package com.example.meetfake.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class RoomExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tbl_room
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tbl_room
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tbl_room
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_room
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public RoomExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_room
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_room
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_room
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_room
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_room
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_room
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_room
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_room
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_room
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_room
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tbl_room
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andRoomidIsNull() {
			addCriterion("roomId is null");
			return (Criteria) this;
		}

		public Criteria andRoomidIsNotNull() {
			addCriterion("roomId is not null");
			return (Criteria) this;
		}

		public Criteria andRoomidEqualTo(String value) {
			addCriterion("roomId =", value, "roomid");
			return (Criteria) this;
		}

		public Criteria andRoomidNotEqualTo(String value) {
			addCriterion("roomId <>", value, "roomid");
			return (Criteria) this;
		}

		public Criteria andRoomidGreaterThan(String value) {
			addCriterion("roomId >", value, "roomid");
			return (Criteria) this;
		}

		public Criteria andRoomidGreaterThanOrEqualTo(String value) {
			addCriterion("roomId >=", value, "roomid");
			return (Criteria) this;
		}

		public Criteria andRoomidLessThan(String value) {
			addCriterion("roomId <", value, "roomid");
			return (Criteria) this;
		}

		public Criteria andRoomidLessThanOrEqualTo(String value) {
			addCriterion("roomId <=", value, "roomid");
			return (Criteria) this;
		}

		public Criteria andRoomidLike(String value) {
			addCriterion("roomId like", value, "roomid");
			return (Criteria) this;
		}

		public Criteria andRoomidNotLike(String value) {
			addCriterion("roomId not like", value, "roomid");
			return (Criteria) this;
		}

		public Criteria andRoomidIn(List<String> values) {
			addCriterion("roomId in", values, "roomid");
			return (Criteria) this;
		}

		public Criteria andRoomidNotIn(List<String> values) {
			addCriterion("roomId not in", values, "roomid");
			return (Criteria) this;
		}

		public Criteria andRoomidBetween(String value1, String value2) {
			addCriterion("roomId between", value1, value2, "roomid");
			return (Criteria) this;
		}

		public Criteria andRoomidNotBetween(String value1, String value2) {
			addCriterion("roomId not between", value1, value2, "roomid");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Byte value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Byte value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Byte value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Byte value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Byte value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Byte> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Byte> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Byte value1, Byte value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andHostIsNull() {
			addCriterion("host is null");
			return (Criteria) this;
		}

		public Criteria andHostIsNotNull() {
			addCriterion("host is not null");
			return (Criteria) this;
		}

		public Criteria andHostEqualTo(Long value) {
			addCriterion("host =", value, "host");
			return (Criteria) this;
		}

		public Criteria andHostNotEqualTo(Long value) {
			addCriterion("host <>", value, "host");
			return (Criteria) this;
		}

		public Criteria andHostGreaterThan(Long value) {
			addCriterion("host >", value, "host");
			return (Criteria) this;
		}

		public Criteria andHostGreaterThanOrEqualTo(Long value) {
			addCriterion("host >=", value, "host");
			return (Criteria) this;
		}

		public Criteria andHostLessThan(Long value) {
			addCriterion("host <", value, "host");
			return (Criteria) this;
		}

		public Criteria andHostLessThanOrEqualTo(Long value) {
			addCriterion("host <=", value, "host");
			return (Criteria) this;
		}

		public Criteria andHostIn(List<Long> values) {
			addCriterion("host in", values, "host");
			return (Criteria) this;
		}

		public Criteria andHostNotIn(List<Long> values) {
			addCriterion("host not in", values, "host");
			return (Criteria) this;
		}

		public Criteria andHostBetween(Long value1, Long value2) {
			addCriterion("host between", value1, value2, "host");
			return (Criteria) this;
		}

		public Criteria andHostNotBetween(Long value1, Long value2) {
			addCriterion("host not between", value1, value2, "host");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNull() {
			addCriterion("created_at is null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNotNull() {
			addCriterion("created_at is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtEqualTo(Date value) {
			addCriterion("created_at =", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotEqualTo(Date value) {
			addCriterion("created_at <>", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThan(Date value) {
			addCriterion("created_at >", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("created_at >=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThan(Date value) {
			addCriterion("created_at <", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
			addCriterion("created_at <=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIn(List<Date> values) {
			addCriterion("created_at in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotIn(List<Date> values) {
			addCriterion("created_at not in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtBetween(Date value1, Date value2) {
			addCriterion("created_at between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
			addCriterion("created_at not between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNull() {
			addCriterion("updated_at is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNotNull() {
			addCriterion("updated_at is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtEqualTo(Date value) {
			addCriterion("updated_at =", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotEqualTo(Date value) {
			addCriterion("updated_at <>", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThan(Date value) {
			addCriterion("updated_at >", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("updated_at >=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThan(Date value) {
			addCriterion("updated_at <", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
			addCriterion("updated_at <=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIn(List<Date> values) {
			addCriterion("updated_at in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotIn(List<Date> values) {
			addCriterion("updated_at not in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtBetween(Date value1, Date value2) {
			addCriterion("updated_at between", value1, value2, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
			addCriterion("updated_at not between", value1, value2, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andStartIsNull() {
			addCriterion("start is null");
			return (Criteria) this;
		}

		public Criteria andStartIsNotNull() {
			addCriterion("start is not null");
			return (Criteria) this;
		}

		public Criteria andStartEqualTo(String value) {
			addCriterion("start =", value, "start");
			return (Criteria) this;
		}

		public Criteria andStartNotEqualTo(String value) {
			addCriterion("start <>", value, "start");
			return (Criteria) this;
		}

		public Criteria andStartGreaterThan(String value) {
			addCriterion("start >", value, "start");
			return (Criteria) this;
		}

		public Criteria andStartGreaterThanOrEqualTo(String value) {
			addCriterion("start >=", value, "start");
			return (Criteria) this;
		}

		public Criteria andStartLessThan(String value) {
			addCriterion("start <", value, "start");
			return (Criteria) this;
		}

		public Criteria andStartLessThanOrEqualTo(String value) {
			addCriterion("start <=", value, "start");
			return (Criteria) this;
		}

		public Criteria andStartLike(String value) {
			addCriterion("start like", value, "start");
			return (Criteria) this;
		}

		public Criteria andStartNotLike(String value) {
			addCriterion("start not like", value, "start");
			return (Criteria) this;
		}

		public Criteria andStartIn(List<String> values) {
			addCriterion("start in", values, "start");
			return (Criteria) this;
		}

		public Criteria andStartNotIn(List<String> values) {
			addCriterion("start not in", values, "start");
			return (Criteria) this;
		}

		public Criteria andStartBetween(String value1, String value2) {
			addCriterion("start between", value1, value2, "start");
			return (Criteria) this;
		}

		public Criteria andStartNotBetween(String value1, String value2) {
			addCriterion("start not between", value1, value2, "start");
			return (Criteria) this;
		}

		public Criteria andEndIsNull() {
			addCriterion("end is null");
			return (Criteria) this;
		}

		public Criteria andEndIsNotNull() {
			addCriterion("end is not null");
			return (Criteria) this;
		}

		public Criteria andEndEqualTo(String value) {
			addCriterion("end =", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndNotEqualTo(String value) {
			addCriterion("end <>", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndGreaterThan(String value) {
			addCriterion("end >", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndGreaterThanOrEqualTo(String value) {
			addCriterion("end >=", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndLessThan(String value) {
			addCriterion("end <", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndLessThanOrEqualTo(String value) {
			addCriterion("end <=", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndLike(String value) {
			addCriterion("end like", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndNotLike(String value) {
			addCriterion("end not like", value, "end");
			return (Criteria) this;
		}

		public Criteria andEndIn(List<String> values) {
			addCriterion("end in", values, "end");
			return (Criteria) this;
		}

		public Criteria andEndNotIn(List<String> values) {
			addCriterion("end not in", values, "end");
			return (Criteria) this;
		}

		public Criteria andEndBetween(String value1, String value2) {
			addCriterion("end between", value1, value2, "end");
			return (Criteria) this;
		}

		public Criteria andEndNotBetween(String value1, String value2) {
			addCriterion("end not between", value1, value2, "end");
			return (Criteria) this;
		}

		public Criteria andStarttimeIsNull() {
			addCriterion("startTime is null");
			return (Criteria) this;
		}

		public Criteria andStarttimeIsNotNull() {
			addCriterion("startTime is not null");
			return (Criteria) this;
		}

		public Criteria andStarttimeEqualTo(String value) {
			addCriterion("startTime =", value, "starttime");
			return (Criteria) this;
		}

		public Criteria andStarttimeNotEqualTo(String value) {
			addCriterion("startTime <>", value, "starttime");
			return (Criteria) this;
		}

		public Criteria andStarttimeGreaterThan(String value) {
			addCriterion("startTime >", value, "starttime");
			return (Criteria) this;
		}

		public Criteria andStarttimeGreaterThanOrEqualTo(String value) {
			addCriterion("startTime >=", value, "starttime");
			return (Criteria) this;
		}

		public Criteria andStarttimeLessThan(String value) {
			addCriterion("startTime <", value, "starttime");
			return (Criteria) this;
		}

		public Criteria andStarttimeLessThanOrEqualTo(String value) {
			addCriterion("startTime <=", value, "starttime");
			return (Criteria) this;
		}

		public Criteria andStarttimeLike(String value) {
			addCriterion("startTime like", value, "starttime");
			return (Criteria) this;
		}

		public Criteria andStarttimeNotLike(String value) {
			addCriterion("startTime not like", value, "starttime");
			return (Criteria) this;
		}

		public Criteria andStarttimeIn(List<String> values) {
			addCriterion("startTime in", values, "starttime");
			return (Criteria) this;
		}

		public Criteria andStarttimeNotIn(List<String> values) {
			addCriterion("startTime not in", values, "starttime");
			return (Criteria) this;
		}

		public Criteria andStarttimeBetween(String value1, String value2) {
			addCriterion("startTime between", value1, value2, "starttime");
			return (Criteria) this;
		}

		public Criteria andStarttimeNotBetween(String value1, String value2) {
			addCriterion("startTime not between", value1, value2, "starttime");
			return (Criteria) this;
		}

		public Criteria andEndtimeIsNull() {
			addCriterion("endTime is null");
			return (Criteria) this;
		}

		public Criteria andEndtimeIsNotNull() {
			addCriterion("endTime is not null");
			return (Criteria) this;
		}

		public Criteria andEndtimeEqualTo(String value) {
			addCriterion("endTime =", value, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeNotEqualTo(String value) {
			addCriterion("endTime <>", value, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeGreaterThan(String value) {
			addCriterion("endTime >", value, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeGreaterThanOrEqualTo(String value) {
			addCriterion("endTime >=", value, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeLessThan(String value) {
			addCriterion("endTime <", value, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeLessThanOrEqualTo(String value) {
			addCriterion("endTime <=", value, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeLike(String value) {
			addCriterion("endTime like", value, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeNotLike(String value) {
			addCriterion("endTime not like", value, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeIn(List<String> values) {
			addCriterion("endTime in", values, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeNotIn(List<String> values) {
			addCriterion("endTime not in", values, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeBetween(String value1, String value2) {
			addCriterion("endTime between", value1, value2, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeNotBetween(String value1, String value2) {
			addCriterion("endTime not between", value1, value2, "endtime");
			return (Criteria) this;
		}

		public Criteria andDaysofweekIsNull() {
			addCriterion("daysOfWeek is null");
			return (Criteria) this;
		}

		public Criteria andDaysofweekIsNotNull() {
			addCriterion("daysOfWeek is not null");
			return (Criteria) this;
		}

		public Criteria andDaysofweekEqualTo(String value) {
			addCriterion("daysOfWeek =", value, "daysofweek");
			return (Criteria) this;
		}

		public Criteria andDaysofweekNotEqualTo(String value) {
			addCriterion("daysOfWeek <>", value, "daysofweek");
			return (Criteria) this;
		}

		public Criteria andDaysofweekGreaterThan(String value) {
			addCriterion("daysOfWeek >", value, "daysofweek");
			return (Criteria) this;
		}

		public Criteria andDaysofweekGreaterThanOrEqualTo(String value) {
			addCriterion("daysOfWeek >=", value, "daysofweek");
			return (Criteria) this;
		}

		public Criteria andDaysofweekLessThan(String value) {
			addCriterion("daysOfWeek <", value, "daysofweek");
			return (Criteria) this;
		}

		public Criteria andDaysofweekLessThanOrEqualTo(String value) {
			addCriterion("daysOfWeek <=", value, "daysofweek");
			return (Criteria) this;
		}

		public Criteria andDaysofweekLike(String value) {
			addCriterion("daysOfWeek like", value, "daysofweek");
			return (Criteria) this;
		}

		public Criteria andDaysofweekNotLike(String value) {
			addCriterion("daysOfWeek not like", value, "daysofweek");
			return (Criteria) this;
		}

		public Criteria andDaysofweekIn(List<String> values) {
			addCriterion("daysOfWeek in", values, "daysofweek");
			return (Criteria) this;
		}

		public Criteria andDaysofweekNotIn(List<String> values) {
			addCriterion("daysOfWeek not in", values, "daysofweek");
			return (Criteria) this;
		}

		public Criteria andDaysofweekBetween(String value1, String value2) {
			addCriterion("daysOfWeek between", value1, value2, "daysofweek");
			return (Criteria) this;
		}

		public Criteria andDaysofweekNotBetween(String value1, String value2) {
			addCriterion("daysOfWeek not between", value1, value2, "daysofweek");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tbl_room
	 * @mbg.generated  Sun Oct 31 14:47:11 ICT 2021
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_room
     *
     * @mbg.generated do_not_delete_during_merge Wed Sep 15 11:23:49 ICT 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}