package com.example.meetfake.model;

import java.util.Date;

public class Tracking {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tracking.id
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tracking.user_id
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tracking.room_id
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    private Long roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tracking.start
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    private String start;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tracking.end
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    private String end;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tracking.ip
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tracking.created_at
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tracking.updated_at
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tracking.id
     *
     * @return the value of tbl_tracking.id
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tracking.id
     *
     * @param id the value for tbl_tracking.id
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tracking.user_id
     *
     * @return the value of tbl_tracking.user_id
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tracking.user_id
     *
     * @param userId the value for tbl_tracking.user_id
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tracking.room_id
     *
     * @return the value of tbl_tracking.room_id
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    public Long getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tracking.room_id
     *
     * @param roomId the value for tbl_tracking.room_id
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    public void setRoomId(Long roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tracking.start
     *
     * @return the value of tbl_tracking.start
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    public String getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tracking.start
     *
     * @param start the value for tbl_tracking.start
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    public void setStart(String start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tracking.end
     *
     * @return the value of tbl_tracking.end
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    public String getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tracking.end
     *
     * @param end the value for tbl_tracking.end
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    public void setEnd(String end) {
        this.end = end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tracking.ip
     *
     * @return the value of tbl_tracking.ip
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tracking.ip
     *
     * @param ip the value for tbl_tracking.ip
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tracking.created_at
     *
     * @return the value of tbl_tracking.created_at
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tracking.created_at
     *
     * @param createdAt the value for tbl_tracking.created_at
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tracking.updated_at
     *
     * @return the value of tbl_tracking.updated_at
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tracking.updated_at
     *
     * @param updatedAt the value for tbl_tracking.updated_at
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}