package com.example.meetfake.model;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_user.id
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_user.email
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_user.fullname
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	private String fullname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_user.phone
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_user.address
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_user.password
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_user.token
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	private String token;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_user.created_at
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_user.updated_at
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_user.id
	 * @return  the value of tbl_user.id
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_user.id
	 * @param id  the value for tbl_user.id
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_user.email
	 * @return  the value of tbl_user.email
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_user.email
	 * @param email  the value for tbl_user.email
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_user.fullname
	 * @return  the value of tbl_user.fullname
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	public String getFullname() {
		return fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_user.fullname
	 * @param fullname  the value for tbl_user.fullname
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_user.phone
	 * @return  the value of tbl_user.phone
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_user.phone
	 * @param phone  the value for tbl_user.phone
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_user.address
	 * @return  the value of tbl_user.address
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_user.address
	 * @param address  the value for tbl_user.address
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_user.password
	 * @return  the value of tbl_user.password
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_user.password
	 * @param password  the value for tbl_user.password
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_user.token
	 * @return  the value of tbl_user.token
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	public String getToken() {
		return token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_user.token
	 * @param token  the value for tbl_user.token
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	public void setToken(String token) {
		this.token = token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_user.created_at
	 * @return  the value of tbl_user.created_at
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_user.created_at
	 * @param createdAt  the value for tbl_user.created_at
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_user.updated_at
	 * @return  the value of tbl_user.updated_at
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_user.updated_at
	 * @param updatedAt  the value for tbl_user.updated_at
	 * @mbg.generated  Sun Oct 24 18:59:45 ICT 2021
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}