package com.example.meetfake.model;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_user.id
	 * @mbg.generated  Fri Sep 17 19:16:26 ICT 2021
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_user.email
	 * @mbg.generated  Fri Sep 17 19:16:26 ICT 2021
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_user.fullname
	 * @mbg.generated  Fri Sep 17 19:16:26 ICT 2021
	 */
	private String fullname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_user.password
	 * @mbg.generated  Fri Sep 17 19:16:26 ICT 2021
	 */
	private String password;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_user.id
	 * @return  the value of tbl_user.id
	 * @mbg.generated  Fri Sep 17 19:16:26 ICT 2021
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_user.id
	 * @param id  the value for tbl_user.id
	 * @mbg.generated  Fri Sep 17 19:16:26 ICT 2021
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_user.email
	 * @return  the value of tbl_user.email
	 * @mbg.generated  Fri Sep 17 19:16:26 ICT 2021
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_user.email
	 * @param email  the value for tbl_user.email
	 * @mbg.generated  Fri Sep 17 19:16:26 ICT 2021
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_user.fullname
	 * @return  the value of tbl_user.fullname
	 * @mbg.generated  Fri Sep 17 19:16:26 ICT 2021
	 */
	public String getFullname() {
		return fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_user.fullname
	 * @param fullname  the value for tbl_user.fullname
	 * @mbg.generated  Fri Sep 17 19:16:26 ICT 2021
	 */
	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_user.password
	 * @return  the value of tbl_user.password
	 * @mbg.generated  Fri Sep 17 19:16:26 ICT 2021
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_user.password
	 * @param password  the value for tbl_user.password
	 * @mbg.generated  Fri Sep 17 19:16:26 ICT 2021
	 */
	public void setPassword(String password) {
		this.password = password;
	}
}