package com.example.meetfake.mapper;

import com.example.meetfake.model.Room;
import com.example.meetfake.model.RoomExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface RoomMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_room
	 * @mbg.generated  Fri Sep 17 19:16:26 ICT 2021
	 */
	long countByExample(RoomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_room
	 * @mbg.generated  Fri Sep 17 19:16:26 ICT 2021
	 */
	int deleteByExample(RoomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_room
	 * @mbg.generated  Fri Sep 17 19:16:26 ICT 2021
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_room
	 * @mbg.generated  Fri Sep 17 19:16:26 ICT 2021
	 */
	int insert(Room record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_room
	 * @mbg.generated  Fri Sep 17 19:16:26 ICT 2021
	 */
	int insertSelective(Room record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_room
	 * @mbg.generated  Fri Sep 17 19:16:26 ICT 2021
	 */
	List<Room> selectByExample(RoomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_room
	 * @mbg.generated  Fri Sep 17 19:16:26 ICT 2021
	 */
	Room selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_room
	 * @mbg.generated  Fri Sep 17 19:16:26 ICT 2021
	 */
	int updateByExampleSelective(@Param("record") Room record, @Param("example") RoomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_room
	 * @mbg.generated  Fri Sep 17 19:16:26 ICT 2021
	 */
	int updateByExample(@Param("record") Room record, @Param("example") RoomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_room
	 * @mbg.generated  Fri Sep 17 19:16:26 ICT 2021
	 */
	int updateByPrimaryKeySelective(Room record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_room
	 * @mbg.generated  Fri Sep 17 19:16:26 ICT 2021
	 */
	int updateByPrimaryKey(Room record);
}