package com.example.meetfake.mapper;

import com.example.meetfake.model.Tracking;
import com.example.meetfake.model.TrackingExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface TrackingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tracking
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    long countByExample(TrackingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tracking
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    int deleteByExample(TrackingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tracking
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tracking
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    int insert(Tracking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tracking
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    int insertSelective(Tracking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tracking
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    List<Tracking> selectByExample(TrackingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tracking
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    Tracking selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tracking
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    int updateByExampleSelective(@Param("record") Tracking record, @Param("example") TrackingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tracking
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    int updateByExample(@Param("record") Tracking record, @Param("example") TrackingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tracking
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    int updateByPrimaryKeySelective(Tracking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tracking
     *
     * @mbg.generated Sun Oct 31 14:47:11 ICT 2021
     */
    int updateByPrimaryKey(Tracking record);
}