package com.example.meetfake.mapper;

import com.example.meetfake.model.User;
import com.example.meetfake.model.UserExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_user
	 * @mbg.generated  Wed Sep 15 11:26:16 ICT 2021
	 */
	long countByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_user
	 * @mbg.generated  Wed Sep 15 11:26:16 ICT 2021
	 */
	int deleteByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_user
	 * @mbg.generated  Wed Sep 15 11:26:16 ICT 2021
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_user
	 * @mbg.generated  Wed Sep 15 11:26:16 ICT 2021
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_user
	 * @mbg.generated  Wed Sep 15 11:26:16 ICT 2021
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_user
	 * @mbg.generated  Wed Sep 15 11:26:16 ICT 2021
	 */
	List<User> selectByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_user
	 * @mbg.generated  Wed Sep 15 11:26:16 ICT 2021
	 */
	User selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_user
	 * @mbg.generated  Wed Sep 15 11:26:16 ICT 2021
	 */
	int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_user
	 * @mbg.generated  Wed Sep 15 11:26:16 ICT 2021
	 */
	int updateByExample(@Param("record") User record, @Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_user
	 * @mbg.generated  Wed Sep 15 11:26:16 ICT 2021
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_user
	 * @mbg.generated  Wed Sep 15 11:26:16 ICT 2021
	 */
	int updateByPrimaryKey(User record);
}